import {upcomingPolicyEvents,policyEventText} from './policy-events';
import {cnValuationAudit} from './data-quality';
import {useState} from 'react';
import TrendChart from '../../components/trend/TrendChart';
import {useMarketData} from './use-market-data';
import {observationSnapshot,observationText,observationLink} from './observation-model';
import {referencesFor,windowSeries,yRangeFor,type Market,type WindowYears} from './dashboard-model';
import {upcomingEvents,localEventTime,calendarSource,calendarVerified,calendarExpired} from './events';
export default function ObservationPanel({market,today}:{market:Market;today:string}){
 const data=useMarketData(market,true),[group,setGroup]=useState('growth'),[years,setYears]=useState<WindowYears>(3);
 const snapshot=observationSnapshot(market,data.series,data.indices,today),selected=snapshot.groups.find(x=>x.id===group)!,events=upcomingEvents(new Date().toISOString());
 return <section className="md-observations" aria-label="组合观察与最近变化">
  <header className="md-heading"><div><h2>组合观察</h2><p>当前读数与历史曲线一起看，每项保留自己的单位和所属期。</p></div><a href={`/agent?macro=1&market=${market}`}>宏观追问 ↗</a></header>
  <div className="md-observation-summary"><section><h3>{snapshot.heading}</h3><p className="md-meta">按最近有效观测日期排序；不代表新发布，也不代表这些变化同日发生。</p>{snapshot.changes.length?<ul>{snapshot.changes.slice(0,4).map(row=><li key={row.key}><a href={observationLink(market,row.key)}>{observationText(row)}</a></li>)}</ul>:<p role="status">暂无可比较的前后观测，不能概括变化。</p>}</section><section><h3>证据与缺项</h3><p>现有读数 {snapshot.available}/{snapshot.total} 项。四组均显示；缺项不会填零。</p><p className="md-meta">盈利预期、ETF净资金流尚缺；中国信用/波动预期、美国FINRA融资尚未接入。历史盈利收益率已单列，不能代替盈利预测。不同频率资料并排观察，不能直接拼成市场结论。</p>{data.contextUnavailable&&<p className="md-warning">补充数据接口尚未可用，融资细项与期限差保留缺口。</p>}{data.failed&&<p className="md-warning" role="status">部分资料读取失败。<button onClick={data.retry}>重新读取资料</button></p>}<details open={snapshot.conflicts.length>0}><summary>同段不一致观察（{snapshot.conflicts.length}项）</summary>{snapshot.conflicts.length?snapshot.conflicts.map(x=><p className="md-warning" key={x}>{x}</p>):<p>未形成指数上涨且融资占比 / VIX / 信用利差同段上升的提示；共同日期不足也会无法比较，不代表没有风险。</p>}</details><details><summary>近期已核事件</summary><ul>{upcomingPolicyEvents(market,today).map(e=><li key={e.id}>{policyEventText(e)} · {e.reading} <a href={e.source} target="_blank" rel="noreferrer">官方安排 ↗</a></li>)}</ul><p className="md-meta">核查2026-10-04；选定2026年末日历快照，安排可能改期；实际值与一致预期未接入，不判断超预期。</p>{market==='us'?<><p>选定BLS2026日历，核查{calendarVerified}；{calendarExpired(today)?'快照已过期，请先核官方安排':'临近发布仍需核是否改期'}。</p><ul>{events.map(e=><li key={e.at}>{e.name} · 所属{e.period} · 美东{localEventTime(e.at,'America/New_York')} / 中国{localEventTime(e.at,'Asia/Shanghai')}</li>)}</ul>{!events.length&&<p>快照中没有剩余安排，不代表近期无事件。</p>}<a href={calendarSource} target="_blank" rel="noreferrer">核官方日历 ↗</a></>:<p>已补选定中国发布安排；这不是完整日历。月度指标所属期与计划发布时间分开。</p>}</details></section></div>
  <div className="md-comparison-controls" aria-label="观察组合">{snapshot.groups.map(x=><button key={x.id} aria-pressed={group===x.id} onClick={()=>setGroup(x.id)}>{x.title}</button>)}<label>组合图区间<select value={years} onChange={e=>setYears(e.target.value==='all'?'all':Number(e.target.value) as 1|3)}><option value={1}>近1年</option><option value={3}>近3年</option><option value="all">已取得全部</option></select></label></div>
  <p><strong>{selected.purpose}</strong></p>
  <div className="md-combo-grid">{selected.rows.map(row=>{const s=row.series?windowSeries(row.series,years):undefined,refs=row.metric&&s?referencesFor(row.key,s):[];return <article key={row.key} className="md-card md-combo-card"><h3>{row.title}</h3><p className={row.reading?'md-combo-value':'md-empty'}>{observationText(row)}</p>{row.reading&&s?<div role="img" aria-label={`${row.title}组合历史图`}><TrendChart dates={row.frequency==='月'?s.dates.map(d=>d.slice(0,7)):s.dates} series={[{name:row.title,values:s.values,color:'#527db8'}]} unit={row.unit} markLines={refs.map(r=>({...r,label:r.kind==='定义线'?r.label:r.label.split(' · ')[0]}))} yRange={yRangeFor(s,refs)} height={200}/></div>:<p className="md-meta">{data.pending?'正在读取已有资料…':'未取得合格连续输入，暂不画曲线。'}</p>}<p className={/不一致|市盈率口径/.test(row.quality)?"md-warning":"md-meta"}>{row.quality}</p>{row.series?.source?.source_url&&<a href={row.series.source.source_url} target="_blank" rel="noreferrer">核供方与系列 ↗</a>}{row.key==='finra_margin'&&<p className="md-meta">{data.gaps.finra_margin?.reason??'官方月度资料已核，应用使用范围待明确。'} <a href="https://www.finra.org/rules-guidance/key-topics/margin-accounts/margin-statistics" target="_blank" rel="noreferrer">官方统计 ↗</a></p>}{row.key==='pe_cn'&&<a href={cnValuationAudit.url} target="_blank" rel="noreferrer">官方月报口径核查（{cnValuationAudit.period}）↗</a>}{row.metric&&<details><summary>升降怎么看 · 参考线与来源</summary><p>{row.metric.reading}</p>{refs.map(r=><p key={r.label}><strong style={{color:r.color}}>{r.label}</strong>：{r.explanation} {r.basis}</p>)}<p>来源路径：{row.metric.source}；可定位定义不等于逐期数值和投资阈值已经验证。</p></details>}{row.metric&&<a href={`/market-understanding?market=${market}&metric=${row.key}#index-comparison`}>与指数对照 ↗</a>}</article>})}</div>
  <div className="md-combo-reading"><p><span className="md-tone-opportunity">环境支持 / 机会观察</span> 与 <span className="md-tone-risk">风险压力</span> 的读法：{selected.reading}</p><p><strong>反例与核查：</strong>{selected.counterexample}</p><p className="md-meta">组合曲线分别截止各自最近观测，不代表同一天更新；参考线仅沿用可定位定义或当前窗口历史分位。盈利预测与资金流缺失时，对应组合只完成部分观察。</p></div>
 </section>;
}
